[project]
name = "sending-cloudwatch-logs-to-splunk-using-aws-lambda"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.59",
    "boto3-stubs==1.40.59",
    "requests>=2.32.5",
    "urllib3>=2.5.0",
]
